name: Build

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display go version
        run: go version
      - name: make build
        run: make build
