name: goreleaser

on: 
  push:
    tags:
      - '**'
permissions:
    contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            ref: ${{ github.event.inputs.release_tag }}

      - name: Setup go env
        uses: actions/setup-go@v5
        with: 
          go-version: "1.20"

      - name: Set wasm env version
        run: echo "COSMWASM_VERSION=$(go list -m github.com/CosmWasm/wasmvm | sed 's/.* //')" >> $GITHUB_ENV

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --release-notes ./RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}