name: Lint
# Lint runs golangci-lint over the entire passage3d repository
# This workflow is run on every pull request and push to master
# The `golangci` will pass without running if no *.{go, mod, sum} files have been changed.
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
        if: env.GIT_DIFF
