name: Tests

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    name: Tests and code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.0.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: run tests and generate coverage
        run: make test-cover
        if: env.GIT_DIFF
      - name: Upload codecov report
        uses: codecov/codecov-action@v3.0.0
        with:
          file: coverage.txt
        if: env.GIT_DIFF

